import CustomCursor from "./components/motion/CustomCursor";
import Navbar from "./components/Nav";
import "./globals.css";
import { Poppins } from "next/font/google";
import ThemeController from "./components/motion/ThemeController";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "800"],
  display: "swap",
});

export const metadata = {
  title: "Iqbal Hafid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <CustomCursor />
        <Navbar />
        {children}
        <ThemeController />
      </body>
    </html>
  );
}
